### ISSUE TITLE
Could not find a file named "pubspec.yaml" in git://github.com/simplezhli/flutter_2d_amap.git 136e0c2da1a00dc9180a0d452e593ac89d47b3e8.

### ISSUE THREAD

**Issue by HJJKnight** [simplezhli/flutter_2d_amap#1]
用vscode导入项目，并获取packages时，提示Could not find a file named "pubspec.yaml" in git://github.com/simplezhli/flutter_2d_amap.git 136e0c2da1a00dc9180a0d452e593ac89d47b3e8. pub get failed

**Comment by simplezhli** [comment]
我搜了一下相关问题，你可以试试删除flutter SDK目录下的.pub-cache下边的git文件夹。或者url使用https://github.com/simplezhli/flutter_2d_amap.git
