### ISSUE TITLE
关键词搜索不出来

### ISSUE THREAD

**Issue by paradoxie** [simplezhli/flutter_2d_amap#10]
输入关键词没有任何结果返回，测试输入【卧槽】只返回了一个地址，emmmm....请教下是什么地方的问题呢

**Comment by simplezhli** [comment]
@paradoxie 如果有返回结果，证明是正常的。至于搜索不到的原因，可能是关键词过长，或者我写的POI分类码不全造成的。

**Comment by simplezhli** [comment]
![image](https://user-images.githubusercontent.com/12456431/81526022-06ac9e00-9389-11ea-9a8d-55d00321cced.png)

**Comment by paradoxie** [comment]
> @paradoxie 如果有返回结果，证明是正常的。至于搜索不到的原因，可能是关键词过长，或者我写的POI分类码不全造成的。

感谢回复(*^__^*)

应该不至于POI类型不全，测试采用的是关键词是【中兴】【华为】，我查看了源码AMap2DView类里面的SEARCH_CONTENT多着呢。
我尝试修改了AMap2DView里面的search方法，加上了城市编码的参数接收就能正常返回了，我也看了高德的文档，默认全国，但是目前我这边的现象就是如果不写城市编码基本就没有结果。

建议在AMap2DController将search方法中加入cityCode作为可选参数，默认全国没有问题的倒也不用传这个值。

**Comment by simplezhli** [comment]
@paradoxie 感谢你的建议，我后面会补充上去的。

**Comment by paradoxie** [comment]
@simplezhli  emmm，又发现一个问题，选择一个地址点后，marker会自动跳到另一个点，Android跳动偏差不大，iOS特别明显。用flutter_deer也测试了，同样存在这个现象。可能是什么原因造成的呢？

**Comment by simplezhli** [comment]
@paradoxie 我的处理就是这样的，点击后进行搜索，再选择POI数据的第一条为最终marker点。这个问题iOS上比较明显。当然也可以做成只能点击地图中已有的位置，其余点击事件不响应。

**Comment by simplezhli** [comment]
@paradoxie 在`search`方法中加入`city`参数（cityname（中文或中文全拼）、citycode均可）。对于iOS跳动明显的问题，我使用了POI 周边查询接口，问题得到了缓解。

**Comment by paradoxie** [comment]
@simplezhli 感谢跟进，我是fork了代码增加了城市参数和POI编码(*^__^*)

**Comment by simplezhli** [comment]
@paradoxie 增加POI编码我没有试过。但是使用POI 周边查询接口是可以的，因为安卓端之前就是查询周边两千米范围地址。iOS这边做了方法的统一。

**Comment by simplezhli** [comment]
https://github.com/simplezhli/flutter_2d_amap/blob/a64770b6716be9b1cd889b102d41729aaf72d933/android/src/main/java/com/weilu/flutter/flutter_2d_amap/AMap2DView.java#L215-L217
