### ISSUE TITLE
AMapSearchKit.h  not found

### ISSUE THREAD

**Issue by maomao1020** [simplezhli/flutter_2d_amap#11]
/Users/jerry/.pub-cache/git/flutter_2d_amap-323fcf8203d89a4235f923a1b53ae1e455c9afb3/ios/Classes/FlutterAMap2D.m:13:9: 'AMapSearchKit/AMapSearchKit.h' file not found

**Comment by maomao1020** [comment]
Flutter 应用 https://github.com/simplezhli/flutter_2d_amap.git 时提示AMapSearchKit.不存在，请问什么原因？

**Comment by simplezhli** [comment]
@maomao1020 我尝试将CocoaPods 升到1.9.3，AMapSearchKit使用7.4.0，并没有出现问题。尝试清除缓存重试：

flutter clean
删除ios目录下的 Podfile.lock和Pods
pod deintegrate
pod repo update
最后重新运行安装
