### ISSUE TITLE
ios的web报错，pc手机模式下没问题，安卓的web不报错

### ISSUE THREAD

**Issue by xiaoshuimao** [simplezhli/flutter_2d_amap#16]
你好，ios的web报错（浏览器选项切换成请求桌面网站没问题），pc手机模式下没问题，安卓的web不报错

初始化失败。
![image](https://user-images.githubusercontent.com/6658087/121624679-86350100-caa4-11eb-9326-ffa80e4a83d7.png)

尝试了下 https://simplezhli.github.io/flutter_deer/  也有同样的问题。
![image](https://user-images.githubusercontent.com/6658087/121628624-22163b00-caac-11eb-9564-910bb61b0962.png)

环境信息：
如图，提示没有方法。

![image](https://user-images.githubusercontent.com/6658087/121625059-51757980-caa5-11eb-8c73-11a488a84f45.png)

请教下该如何修改。

**Comment by simplezhli** [comment]
看起来挺奇怪，我晚上回去排查一下。

**Comment by simplezhli** [comment]
@w567675 我这边测试没有发现问题。看报错信息是web上走进了ios的初始化方法`setKey`。我尝试修改了一下判断顺序，你替换一下试试：
```dart
import 'dart:io';

static Future<bool?> setApiKey({String iOSKey = '', String webKey = ''}) async {
    if (kIsWeb) {
      _webKey = webKey;
    } else {
      if (Platform.isIOS) {
        return _channel.invokeMethod<bool>('setKey', iOSKey);
      }
    }
    return Future.value(true);
  }
```

**Comment by xiaoshuimao** [comment]
@simplezhli 换个判断可以的。谢谢🙏

原来的打印了下的确走到ios判断了

![image](https://user-images.githubusercontent.com/6658087/121983308-b55cb280-cdc3-11eb-9617-ec6b75b1ee73.png)

**Comment by simplezhli** [comment]
好的，我后面同步一下代码。
