### ISSUE TITLE
搜索不起效果

### ISSUE THREAD

**Issue by HuYuee** [simplezhli/flutter_2d_amap#17]
不设置城市编码，搜索不起效果，_aMap2DController.search();方法正常执行。但是一直不回调到onPoiSearched方法内。
通过点击屏幕也无法回调到onPoiSearched方法内

**Comment by simplezhli** [comment]
@HuYuee 你的问题发生在什么平台，提供一些环境信息。设置城市编码可以成功吗？尝试换一下关键字试一下，看是否有异常信息。

**Comment by HuYuee** [comment]
是在ios，我相同的代码复制到你的deer项目中是好使的

**Comment by HuYuee** [comment]
然后也没有异常信息，就是没有任何输出，方法不会执行

**Comment by HuYuee** [comment]
我装的库的版本也是保持和你的demo一致的
![image](https://user-images.githubusercontent.com/12147318/126772553-1f32d9c1-45c4-433a-b9fa-250dff7f0a6f.png)

**Comment by HuYuee** [comment]
![image](https://user-images.githubusercontent.com/12147318/126772506-7ba444e5-0a5e-4201-a847-af8b34ddf4bc.png)

**Comment by HuYuee** [comment]
我对比了pubspec.lock和Podfile.lock都是一样的

**Comment by simplezhli** [comment]
这是我这个项目的demo吗，还是你集成进自己的项目。集成配置的key有没有问题。

**Comment by simplezhli** [comment]
deer正确表示代码本身没有问题。

**Comment by HuYuee** [comment]
我代码用你的key也不行

**Comment by HuYuee** [comment]
是我的项目的，我现在所有配置保持和你一致也不行

**Comment by HuYuee** [comment]
并且我这边初始化第一次onPoiSearched就不执行

**Comment by simplezhli** [comment]
用我的key肯定不行，这都是和应用绑定的。你用xcode运行项目，看有没有地图初始化日志输出。

**Comment by HuYuee** [comment]
![image](https://user-images.githubusercontent.com/12147318/126775047-7c70e066-33e6-4975-9a26-ef6224e33b30.png)

**Comment by HuYuee** [comment]
这是官方给出来的，但是我看了我的search sdk的版本是7.9

**Comment by HuYuee** [comment]
这是xcode运行出来的日志

![image](https://user-images.githubusercontent.com/12147318/126775372-f6beb421-671c-45af-a29f-216132882ee8.png)

**Comment by HuYuee** [comment]
应用和key怎么绑定？在高德地图后台绑定吗？

**Comment by simplezhli** [comment]
https://lbs.amap.com/api/ios-sdk/guide/create-project/get-key

**Comment by HuYuee** [comment]
我知道原因了，我key用错了，差点怀疑人生了。感谢感谢

**Comment by simplezhli** [comment]
。。。我不知道说啥，我一般都不会怀疑这里有问题。

**Comment by HuYuee** [comment]
哈哈
