### ISSUE TITLE
not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by longtaozz** [simplezhli/flutter_2d_amap#2]
android studio：
flutter packages get
Git error. Command: git fetch
fatal: not a git repository (or any of the parent directories): .git

**Comment by simplezhli** [comment]
我并不确定这是什么因素造成的，你可以尝试运行一下https://github.com/simplezhli/flutter_deer 这个项目，看是否会出现同样问题。

**Comment by tennessine** [comment]
@simplezhli 老大能不能给我看个这个问题，我搜了好几天，感觉只有你有能力解决。

代码地址在这里：https://github.com/tennessine/flutter-baidumap
AndroidView所在的widget tree重新build之后，地图就出现了黑边，可能是重复绘制造成的吧。
求解决方案。

**Comment by simplezhli** [comment]
@tennessine  我尝试直接setState不做_active判断并不会发生黑边现象，怀疑是你将组件添加和移除导致的生命周期问题。所以我尝试强行调用onPause与onResume方法，发现问题有所解决。

![image](https://user-images.githubusercontent.com/12456431/61609111-9d3b9180-ac87-11e9-97b4-82e9e9e17c73.png)

**Comment by tennessine** [comment]
@simplezhli 太感谢了，我试试，我已经解决了1个星期了，各种问，好像写插件的比较少啊，我也看了你的代码，确实不错。

**Comment by tennessine** [comment]
@simplezhli 根据你的提示，我解决了，是因为getView时候我每次都返回了新的PlatformView，具体不知道什么原因，但我先实例化了一个PlatformView每次都返回这个创建好的PlatformView就可以了。

**Comment by simplezhli** [comment]
@tennessine 解决了就好

**Comment by tennessine** [comment]
有空还是得参考flutter google map，自己搞坑太多了
