### ISSUE TITLE
发现地图在第一次初始化之后，如果用户不允许开启定位权限。下次再进来并不会重新弹出开启定位权限

### ISSUE THREAD

**Issue by HuYuee** [simplezhli/flutter_2d_amap#20]

**Comment by HuYuee** [comment]
经过测试，只有IOS有问题。Android侧重新打开地图页面会弹出定位权限

**Comment by simplezhli** [comment]
代码只做了简单的权限申请处理，对于实际项目中来说远远不够。这方面可以使用flutter权限相关的插件处理。比如进入地图页面前就做权限申请，成功后再进入页面。

**Comment by HuYuee** [comment]
自己加入了permission_handler解决了。谢谢
