### ISSUE TITLE
iOS高德会报错

### ISSUE THREAD

**Issue by Nemowxy** [simplezhli/flutter_2d_amap#24]
错误内容：
Error Domain=AMapFoundationErrorPrivacyShowUnknow Code=555570 "(null)" UserInfo={info=使用AMapLocationKit SDK 功能前请设置隐私权政策是否弹窗告知用户}
[AMapLocationKit]:Error Domain=AMapFoundationErrorPrivacyShowUnknow Code=555570 "(null)" UserInfo={info=使用AMapLocationKit SDK 功能前请设置隐私权政策是否弹窗告知用户}
Error Domain=AMapFoundationErrorPrivacyShowUnknow Code=555570 "(null)" UserInfo={info=使用AMapSearchKit SDK 功能前请设置隐私权政策是否弹窗告知用户}

查了下，大概是说构造MapView之前要调一个检查合规的接口，看文档是2021-11-25改的
![image](https://user-images.githubusercontent.com/12393700/150485272-df81a283-6f8d-40f9-8526-35a1f42ef5d1.png)
https://lbs.amap.com/api/ios-sdk/guide/create-project/note#t1

**Comment by simplezhli** [comment]
@Nemowxy 好的，我抽时间适配一下这里。

**Comment by simplezhli** [comment]
Android 和iOS我都适配了，注意使用前调用`Flutter2dAMap.updatePrivacy(true);`。你可以再试一下。

**Comment by Nemowxy** [comment]
> 

好的，感谢大佬

**Comment by Nemowxy** [comment]
验证已解决
