### ISSUE TITLE
新版本的HtmlElementView已经支持onPlatformViewCreated方法了

### ISSUE THREAD

**Issue by guchengxi1994** [simplezhli/flutter_2d_amap#25]
![image](https://user-images.githubusercontent.com/33513462/178391369-5daaec0e-18b4-469f-84b2-9f0e014905f6.png)
试过这种方式可以正常调用了

**Comment by simplezhli** [comment]
@guchengxi1994 感谢你的反馈，学到了。

**Comment by guchengxi1994** [comment]
@simplezhli 哪里，今天参考你写的代码，自己还在高德新版本secret key上栽了跟头😂
