### ISSUE TITLE
[!] The 'Pods-Runner' target has frameworks with conflicting names: mamapkit.framework.

### ISSUE THREAD

**Issue by ghost** [simplezhli/flutter_2d_amap#27]
[!] The 'Pods-Runner' target has frameworks with conflicting names: mamapkit.framework.

**Comment by Cmeicloud** [comment]
amap_flutter_map: ^3.0.0 #高德地图
  amap_flutter_location: ^3.0.0 #高德定位
  flutter_2d_amap:
#    git:
#      ref: '9e1d22ec'
#      url: '/Users/mei/developer/FlutterProjects/flutter_2d_amap'
      path: /Users/mei/developer/FlutterProjects/flutter_2d_amap

**Comment by ghost** [comment]
amap_flutter_map: ^3.0.0 #高德地图
  amap_flutter_location: ^3.0.0 #高德定位
  flutter_2d_amap:
      path: /Users/mei/developer/FlutterProjects/flutter_2d_amap

**Comment by simplezhli** [comment]
https://github.com/simplezhli/flutter_2d_amap/blob/3850a4dcf81c0354d034718e876a9732b380fdda/ios/flutter_2d_amap.podspec#L18-L20

看是不是其他两个地图库里面引用了一样的依赖，删掉就行了。

**Comment by ghost** [comment]
感谢回复～ 我原本项目里面集成了官方的插件amap_flutter_map，再集成flutter_2d_amap不行。知道是地图引用冲突了，flutter_2d_amap：里面包含AMap2DMap ，官方amap_flutter_map ：里面包含AMap3DMap。但我项目业务里面已经使用了官方的AMap3DMap，我想两者都用不知有解决办法没？

**Comment by ghost** [comment]
我尝试过删除flutter_2d_amap里面的  s.dependency 'AMap2DMap'  用官方插件里面自带的 AMap3DMap，尝试编译报错。flutter_2d_amap有引用AMap2DMap。

**Comment by simplezhli** [comment]
两个都用这个我就不清楚了，无法帮到你。建议还是留一种。
