### ISSUE TITLE
pod install的时候报这个错误，帮忙看下这个问题

### ISSUE THREAD

**Issue by SuperIOSDeveloper** [simplezhli/flutter_2d_amap#3]
[!] 'AMap2DMap' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

**Comment by simplezhli** [comment]
@SuperIOSDeveloper  这个警告可以忽略。
