### ISSUE TITLE
搜索不会成功的

### ISSUE THREAD

**Issue by MingForce** [simplezhli/flutter_2d_amap#7]
要设置城市编码，关键词搜索才会成功

**Comment by simplezhli** [comment]
不设置城市编码，默认搜索全国范围的。

**Comment by HuYuee** [comment]
我这边不设置城市编码，搜索不起效果，_aMap2DController.search();方法正常执行。但是一直不回调到onPoiSearched方法内。

**Comment by HuYuee** [comment]
@simplezhli

**Comment by HuYuee** [comment]
通过点击屏幕也无法回调到onPoiSearched方法内
