### ISSUE TITLE
这个会支持flutterWeb吗？

### ISSUE THREAD

**Issue by Mecil9** [simplezhli/flutter_2d_amap#9]

**Comment by simplezhli** [comment]
@Mecil9 我还不清楚如何去实现，不过我会尽量支持的。

**Comment by simplezhli** [comment]
已支持Web，欢迎体验。（基本功能使用没问题，地图的覆盖物显示有问题。怀疑是Flutter的兼容问题）

**Comment by Mecil9** [comment]
感谢，已测试。
地图样式类的应用方式，点击展示，动画类的应用展示是否参考js的文档来实现？

**Comment by simplezhli** [comment]
我不理解你的问题。Web的效果尽量与Android、 iOS保持一致，js的文档只是基础用法，至于具体处理由实现的效果决定。

**Comment by Mecil9** [comment]
我的意思是：
地图样式怎么做切换？点击效果和poi点的聚合在web端怎么实现？

**Comment by simplezhli** [comment]
这个插件提供的功能有限，你说的不包含在内。你可以参考我的这篇[博客](https://weilu.blog.csdn.net/article/details/106465792)自行拓展。

**Comment by Mecil9** [comment]
那我建一个分支，一起搞一个？

**Comment by simplezhli** [comment]
Web暂时小问题还比较多，精力有限，我就不参与了。
